<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>MailPulse</RootNamespace>
    <AssemblyName>MailPulse</AssemblyName>
    <Version>0.3.0</Version>
    <ApplicationIcon>Assets\MailPulse.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\MailPulse.ico" />
    <Resource Include="Assets\MailPulse.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.43" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Costura.Fody" Version="5.7.0" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>



